### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by gaurangfgupta** [gaurangfgupta/UniversalEntities#4]
Many entities like **Patient, Employee, ResearchCase** have common properties eg. any person would have a name comprising of _Title, First, Middle and Last_.
So I've created an interface IPersonName (see 'Interfaces' folder) with the 4 properties. Then I created a struct PersonName which contains the usual implementation (formatting, validation etc.) for these properties. Any person class may use this struct. If a different implementation is needed, IPersonName may be used directly or a different struct may be created.
An abstract **Person** class will be created which uses PersonName struct and contains more properties common to a person like contact details. Then entities like **Patient, Employee, ResearchCase** may derive from this class to contain more specific properties.
This approach has 2 advantages for me, namely, re-usability and consistency of property names
@panshul007 Am I on right track?

**Comment by gaurangfgupta** [comment]
Hey @panshul007  I guess you missed the above comment. Please advise me so I may continue further or make amendments as required.

**Comment by pgbytes** [comment]
Sorry for the late reply.. missed the notification for the issue.

The approach to the PersonName class is perfect.

I think u do not need an interface for the data structure. interfaces are used when u might have different implementations for a similar function. for example, calculating BMI based on gender of Person. But in the current case u do not need an interface for the PersonName... Use the class directly. If u need another structure for some reason, just created another class with the different structure.

**Comment by gaurangfgupta** [comment]
Got it. Anyhow I had to remove the structures because Mongo C# driver
doesn't support them
